name: Deployment - Reusable Workflow

on:
  workflow_call:
    inputs:
      mongodb-uri:
        required: true
        type: string
      kubectl-version:
        description: Provide the required kubectl version
        default: v5.1.0
        required: false
        type: string
      k8s-manifest-dir:
        description: Directory containing Kubernetes manifest files
        default: kubernetes/
        required: true
        type: string
      environment:
        description: Deployment environment (e.g., dev, prod)
        default: dev
        required: true
        type: string
    secrets:
      k8s-kubeconfig:
        required: true
      mongodb-password:
        required: true
    outputs:
      application-url:
        value: ${{ jobs.reuse-deploy.outputs.APP_INGRESS_URL }}

jobs:
    reuse-deploy:
      environment:
        name: ${{ inputs.environment }}
        url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
      outputs:
        APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
      runs-on:
        - self-hosted
        - linux

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v7.0.0

        - name: Install Kubectl CLI
          uses: Azure/setup-kubectl@v5.1.0
          with:
            version: ${{ inputs.kubectl-version }}

        - name: Set Kubeconfig
          uses: Azure/k8s-set-context@v5.0.1
          with:
            method: kubeconfig
            kubeconfig: ${{ secrets.k8s-kubeconfig }}

        - name: Fetch Kubernetes Cluster Details
          run: |
            kubectl version
            echo ----------------------
            kubectl get nodes

        - name: Save NGINX Ingress Controller IP
          id: save_ingress_ip
          run: |
            INGRESS_IP=$(kubectl -n ingress-nginx get svc ingress-nginx-controller \
              -o jsonpath='{.status.loadBalancer.ingress[0].ip}')

            if [ -z "$INGRESS_IP" ]; then
              echo "Ingress IP is empty, falling back to localhost"
              INGRESS_IP="127.0.0.1"
            fi

            echo "INGRESS_IP=$INGRESS_IP" >> $GITHUB_ENV

        - name: Replace tokens in Manifest files
          uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '_{_'
            tokenSuffix: '_}_'
            files: '["${{ inputs.k8s-manifest-dir }}*.yaml"]'
          env:
            NAMESPACE: ${{ vars.NAMESPACE }}
            REPLICAS: ${{ vars.REPLICAS }}
            IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
            INGRESS_IP: ${{ env.INGRESS_IP }}

        - name: Check files
          run: |
            cat ${{ inputs.k8s-manifest-dir }}*.yaml
        
        - name: Create MongoDB secret
          run: |
            kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
              --from-literal=MONGO_URI=${{ inputs.mongodb-uri }} \
              --from-literal=MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
              --from-literal=MONGO_PASSWORD=${{ secrets.mongodb-password }} \
              --save-config \
              --dry-run=client \
              -o yaml | kubectl apply -f -

        - name: Deploy to ${{ inputs.environment }} Env
          run: kubectl apply -f ${{ inputs.k8s-manifest-dir }}

        - name: Set App Ingress Host URL
          id: set-ingress-host-address
          run: |
            echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath='{.items[0].spec.rules[0].host}')" >> "$GITHUB_OUTPUT"